### ISSUE TITLE
Avoid Dict of Any

### ISSUE THREAD

**Issue by scls19fr** [frictionlessdata/TableSchema.jl#35]
https://github.com/frictionlessdata/TableSchema.jl/blob/72f599c7505adcf89bf21f2c767527953320679a/src/constraints.jl#L41

It's generally better to know type of keys and type of values that are stored in a `Dict` (contrary to Python) if you want to have correct performance.

When a `Dict` have values of different types, it's generally better to consider using a `struct`.

https://docs.julialang.org/en/v1/manual/performance-tips/index.html provide good tips to have good performance writing Julia code 

https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Avoid-containers-with-abstract-type-parameters-1

**Comment by loleg** [comment]
We are using `Dict` in this case to create a JSON representation of a `struct`. As per this [JSON type serialization](https://discourse.julialang.org/t/json-type-serialization/9794/6?u=loleg) thread:

> JSON is typically considered an “anonymous type” kind of specification, so there isn’t really a notion of what “type” an object is. 

A more elegant solution here would be to generate JSON directly through introspection, as in the example in the link above. However, there are a couple of places where we need to explicitly map values due to conflicts between the Data Package standard and Julia identifiers. 

If you have a more concrete example of how else to implement this, please add it here. Closing for now.
